using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DefaultDiceData : MonoBehaviour
{
    public enum EffectType
    {
        Blank = 0,
        BlankUnset = 1,
        BlankPetrified = 2,
        BlankUsed = 3,
        BlankItem = 4,
        BlankCurse = 5,
        BlankStasis = 6,
        BlankSticky = 7,
        BlankExert = 8,
        BlankFumble = 9,
        AddCleanseAndSelfCleanse = 10,
        DamageToAllyMandatoryGenerousStasis = 11,
        SelfDamageCantrip = 12,
        IDieCantrip = 13,
        SelfDamageMandatory = 14,
        Damage = 15,
        DamageGrowth = 16,
        DamageEngage = 17,
        DamageManagain = 18,
        DamagePain = 19,
        DamageDeathwish = 20,
        DamageDeath = 21,
        DamageSerrated = 22,
        DamageExert = 23,
        DamageDoubleUse = 24,
        DamageQuadUse = 25,
        DamageBloodlust = 26,
        DamageCopycat = 27,
        DamagePristine = 28,
        DamageGuilt = 29,
        DamageCruel = 30,
        DamageShifter = 31,
        DamageFocus = 32,
        DamageInspired = 33,
        DamageToAll = 34,
        ReviveManagain = 35,
        DamageCleave = 36,
        DamageDescend = 37,
        DamageCleaveChain = 38,
        DamageHeavy = 39,
        DamageInflictSingleUse = 40,
        DamageSteel = 41,
        DamageCharged = 42,
        StunBully = 43,
        DamageVulnerable = 44,
        DamageEra = 45,
        DamageRanged = 46,
        DamageRangedPoison = 47,
        DamageRangedDuplicate = 48,
        DamageRangedCleave = 49,
        DamageRangedCopycat = 50,
        DamageSelfShield = 51,
        DamageSelfHeal = 52,
        DamagePoison = 53,
        DamageToAllPoison = 54,
        DamagePoisonPlague = 55,
        Shield = 56,
        ShieldFlesh = 57,
        ShieldGrowth = 58,
        ShieldEngage = 59,
        ShieldEnduringDeath = 60,
        ShieldManaGain = 61,
        ShieldDoubleUse = 62,
        ShieldSteel = 63,
        ShieldRescue = 64,
        ShieldPristine = 65,
        ShieldCantrip = 66,
        ShieldCopycat = 67,
        ShieldFocus = 68,
        ShieldCleave = 69,
        ShieldCharged = 70,
        ShieldCleanse = 71,
        ShieldToAll = 72,
        ShieldToAllCantrip = 73,
        ShieldAndHeal = 74,
        ShieldSmith = 75,
        Mana = 76,
        ManaCantrip = 77,
        ManaCantripBoned = 78,
        ManaGrowth = 79,
        ManaDecay = 80,
        ManaDeath = 81,
        ManaPain = 82,
        ManaBloodlust = 83,
        ManaPair = 84,
        ManaTrio = 85,
        HealShieldManaGain = 86,
        ManaCharged = 87,
        DamageSingleUseCharged = 88,
        DamageSingleUseInflictPain = 89,
        DamageSingleUseCruel = 90,
        DamageSingleUsePoison = 91,
        DamageSingleUseSelfHeal = 92,
        ManaSingleUse = 93,
        ShieldSingleUsePermaBoost = 94,
        DamageSingleUseWeaken = 95,
        DamageSingleUseFierce = 96,
        DamageSingleUseEcho = 97,
        DamageSingleUseDispel = 98,
        DamageSingleUseInflictExert = 99,
        StunSingleUse = 100,
        DamageSingleUseWeakenVulnerableCleaveEngageSelfheal = 101, // Chaos Wand
        DamageLead = 102,
        Heal = 103,
        HealSingleUse = 104,
        HealVitality = 105,
        HealRescue = 106,
        HealAll = 107,
        HealBoost = 108,
        HealCleave = 109,
        HealRegen = 110,
        HealCleanse = 111,
        HealManaGain = 112,
        HealGroooooowth = 113,
        HealDoubleUse = 114,
        DamageSingleUse = 115,
        KillIfLessThanHp = 116,
        Undying = 117,
        RedirectSelfShield = 118,
        ShieldRepel = 119,
        ShieldRepelRampageRescue = 120,
        ShieldPain = 121,
        KillIfLessThanHpRanged = 122,
        Dodge = 123,
        DodgeCantrip = 124,
        RerollCantrip = 125,
        DamageCantrip = 126,
        DamageStickyMandatoryDeath = 127,
        DamageToAllRampagePain = 128,
        DamageChargedRampagePain = 129,
        Reuse = 130,
        DamageWeaken = 131,
        DamageDuplicate = 132,
        ShieldDuplicate = 133,
        ManaDuplicate = 134,
        DamageRangedEngage = 135,
        Revive = 136,
        DamageRampage = 137,
        AddDoubleUse = 138,
        AddCantrip = 139,
        AddNothing = 140,
        AddCopycat = 141,
        AddCleaveSingleUse = 142,
        AddCruelDeathwish = 143,
        AddManaGain = 144,
        AddPoison = 145,
        AddSelfShield = 146,
        AddSelfHeal = 147,
        AddSelfHealSelfShield = 148,
        AddPainManaGain = 149,
        AddEngage = 150,
        AddGrowth = 151,
        BlankShield = 152,
        BlankDamage = 153,
        BlankMana = 154,
        BlankSummon = 155,
        BlankHeal = 156,
        RedirectCleave = 157, // Red Flag
        DamageToAllRampage = 158, // Spinning Scythe
        DamageFleshPain = 159, // Viscera
        DamageToAllChargedManaCost = 160, // Mana Bomb
        DamageSingleUseInflictSingleUse = 161, // Wand of Wand
        HealBoostInflictPain = 162, // Demon Horn
        DamageHeavyCharged = 163, // Charged Hammer
        HealRegenCleanseManaCost = 164, // Infused Herbs
        DamagePainDrink = 165, // Potion Shard
        ReviveDrink = 166, // Revive Potion
        ManaDrink = 167, // Mana Potion
        DamageEliminate = 168,
        DamagePoisonEnemy = 169,
        DamageEnemy = 170,
        DamageCleaveEnemy = 171,
        SummonDragonsDeath = 172,
        DamageCleaveTrio = 173,
        DamageDefy = 174,
        DamageCritical = 175,
        TargetAlly = 176,
        TargetAllyPips = 177,
        AllAlliesPips = 178,
        AllAllies = 179,
        TargetEnemy = 180,
        TargetEnemyPips = 181,
        AllEnemiesPips = 182,
        AllEnemies = 183,
        TargetAllPips = 184,
        TargetAll = 185,
        TargetSelf = 186,
        TargetSelfPips = 187
    }

    public static readonly Dictionary<string, EffectType> EffectMap = new Dictionary<string, EffectType>
    {
        { "Blank", EffectType.Blank },
        { "Blank (Unset)", EffectType.BlankUnset },
        { "Blank (Petrified)", EffectType.BlankPetrified },
        { "Blank (Used)", EffectType.BlankUsed },
        { "Blank (Item)", EffectType.BlankItem },
        { "Blank (Curse)", EffectType.BlankCurse },
        { "Blank (Stasis)", EffectType.BlankStasis },
        { "Blank (Sticky)", EffectType.BlankSticky },
        { "Blank (Exert)", EffectType.BlankExert },
        { "Blank (Fumble)", EffectType.BlankFumble },
        { "Add Cleanse and SelfCleanse", EffectType.AddCleanseAndSelfCleanse },
        { "Damage to Ally Mandatory Generous Stasis", EffectType.DamageToAllyMandatoryGenerousStasis },
        { "Self damage Cantrip", EffectType.SelfDamageCantrip },
        { "I Die Cantrip", EffectType.IDieCantrip },
        { "Self damage Mandatory", EffectType.SelfDamageMandatory },
        { "Damage", EffectType.Damage },
        { "Damage Growth", EffectType.DamageGrowth },
        { "Damage Engage", EffectType.DamageEngage },
        { "Damage Managain", EffectType.DamageManagain },
        { "Damage Pain", EffectType.DamagePain },
        { "Damage Deathwish", EffectType.DamageDeathwish },
        { "Damage Death", EffectType.DamageDeath },
        { "Damage serrated", EffectType.DamageSerrated },
        { "Damage Exert", EffectType.DamageExert },
        { "Damage DoubleUse", EffectType.DamageDoubleUse },
        { "Damage QuadUse", EffectType.DamageQuadUse },
        { "Damage Bloodlust", EffectType.DamageBloodlust },
        { "Damage Copycat", EffectType.DamageCopycat },
        { "Damage Pristine", EffectType.DamagePristine },
        { "Damage Guilt", EffectType.DamageGuilt },
        { "Damage Cruel", EffectType.DamageCruel },
        { "Damage Shifter", EffectType.DamageShifter },
        { "Damage Focus", EffectType.DamageFocus },
        { "Damage Inspired", EffectType.DamageInspired },
        { "Damage to all", EffectType.DamageToAll },
        { "Revive Managain", EffectType.ReviveManagain },
        { "Damage Cleave", EffectType.DamageCleave },
        { "Damage Descend", EffectType.DamageDescend },
        { "Damage Cleave Chain", EffectType.DamageCleaveChain },
        { "Damage Heavy", EffectType.DamageHeavy },
        { "Damage InflictSingleUse", EffectType.DamageInflictSingleUse },
        { "Damage Steel", EffectType.DamageSteel },
        { "Damage Charged", EffectType.DamageCharged },
        { "Stun Bully", EffectType.StunBully },
        { "Damage Vulnerable", EffectType.DamageVulnerable },
        { "Damage Era", EffectType.DamageEra },
        { "Damage Ranged", EffectType.DamageRanged },
        { "Damage Ranged Poison", EffectType.DamageRangedPoison },
        { "Damage Ranged Duplicate", EffectType.DamageRangedDuplicate },
        { "Damage Ranged Cleave", EffectType.DamageRangedCleave },
        { "Damage Ranged Copycat", EffectType.DamageRangedCopycat },
        { "Damage SelfShield", EffectType.DamageSelfShield },
        { "Damage SelfHeal", EffectType.DamageSelfHeal },
        { "Damage Poison", EffectType.DamagePoison },
        { "Damage to ALL Poison", EffectType.DamageToAllPoison },
        { "Damage Poison Plague", EffectType.DamagePoisonPlague },
        { "Shield", EffectType.Shield },
        { "Shield flesh", EffectType.ShieldFlesh },
        { "Shield Growth", EffectType.ShieldGrowth },
        { "Shield Engage", EffectType.ShieldEngage },
        { "Shield Enduring Death", EffectType.ShieldEnduringDeath },
        { "Shield ManaGain", EffectType.ShieldManaGain },
        { "Shield DoubleUse", EffectType.ShieldDoubleUse },
        { "Shield Steel", EffectType.ShieldSteel },
        { "Shield Rescue", EffectType.ShieldRescue },
        { "Shield Pristine", EffectType.ShieldPristine },
        { "Shield Cantrip", EffectType.ShieldCantrip },
        { "Shield Copycat", EffectType.ShieldCopycat },
        { "Shield Focus", EffectType.ShieldFocus },
        { "Shield Cleave", EffectType.ShieldCleave },
        { "Shield Charged", EffectType.ShieldCharged },
        { "Shield Cleanse", EffectType.ShieldCleanse },
        { "Shield to all", EffectType.ShieldToAll },
        { "Shield to all Cantrip", EffectType.ShieldToAllCantrip },
        { "Shield and Heal", EffectType.ShieldAndHeal },
        { "Shield Smith", EffectType.ShieldSmith },
        { "Mana", EffectType.Mana },
        { "Mana Cantrip", EffectType.ManaCantrip },
        { "Mana Cantrip Boned", EffectType.ManaCantripBoned },
        { "Mana Growth", EffectType.ManaGrowth },
        { "Mana Decay", EffectType.ManaDecay },
        { "Mana Death", EffectType.ManaDeath },
        { "Mana Pain", EffectType.ManaPain },
        { "Mana Bloodlust", EffectType.ManaBloodlust },
        { "Mana Pair", EffectType.ManaPair },
        { "Mana trio", EffectType.ManaTrio },
        { "Heal Shield ManaGain", EffectType.HealShieldManaGain },
        { "Mana Charged", EffectType.ManaCharged },
        { "Damage Single-use Charged", EffectType.DamageSingleUseCharged },
        { "Damage SIngle-use InflictPain", EffectType.DamageSingleUseInflictPain },
        { "Damage SIngle-use Cruel", EffectType.DamageSingleUseCruel },
        { "Damage Single-use Poison", EffectType.DamageSingleUsePoison },
        { "Damage Single-use SelfHeal", EffectType.DamageSingleUseSelfHeal },
        { "Mana Single-use", EffectType.ManaSingleUse },
        { "Shield Single-use PermaBoost", EffectType.ShieldSingleUsePermaBoost },
        { "Damage Single-use Weaken", EffectType.DamageSingleUseWeaken },
        { "Damage Single-use Fierce", EffectType.DamageSingleUseFierce },
        { "Damage Single-use Echo", EffectType.DamageSingleUseEcho },
        { "Damage Single-use Dispel", EffectType.DamageSingleUseDispel },
        { "Damage Single-use InflictExert", EffectType.DamageSingleUseInflictExert },
        { "Stun Single-use", EffectType.StunSingleUse },
        { "Damage Singleuse Weaken Vulnerable Cleave Engage Selfheal - [Chaos Wand]", EffectType.DamageSingleUseWeakenVulnerableCleaveEngageSelfheal },
        { "Damage Lead", EffectType.DamageLead },
        { "Heal", EffectType.Heal },
        { "Heal Single-use", EffectType.HealSingleUse },
        { "Heal Vitality", EffectType.HealVitality },
        { "Heal Rescue", EffectType.HealRescue },
        { "Heal All", EffectType.HealAll },
        { "Heal Boost", EffectType.HealBoost },
        { "Heal Cleave", EffectType.HealCleave },
        { "Heal Regen", EffectType.HealRegen },
        { "Heal Cleanse", EffectType.HealCleanse },
        { "Heal ManaGain", EffectType.HealManaGain },
        { "Heal Groooooowth", EffectType.HealGroooooowth },
        { "Heal DoubleUse", EffectType.HealDoubleUse },
        { "Damage Single-use", EffectType.DamageSingleUse },
        { "Kill if less than hp ", EffectType.KillIfLessThanHp },
        { "Undying", EffectType.Undying },
        { "Redirect SelfShield", EffectType.RedirectSelfShield },
        { "Shield Repel", EffectType.ShieldRepel },
        { "Shield Repel Rampage Rescue", EffectType.ShieldRepelRampageRescue },
        { "Shield Pain", EffectType.ShieldPain },
        { "Kill if less than hp Ranged", EffectType.KillIfLessThanHpRanged },
        { "Dodge", EffectType.Dodge },
        { "Dodge Cantrip", EffectType.DodgeCantrip },
        { "Reroll Cantrip", EffectType.RerollCantrip },
        { "Damage Cantrip", EffectType.DamageCantrip },
        { "Damage Sticky Mandatory Death", EffectType.DamageStickyMandatoryDeath },
        { "Damage to all Rampage Pain", EffectType.DamageToAllRampagePain },
        { "Damage Charged Rampage Pain", EffectType.DamageChargedRampagePain },
        { "Reuse", EffectType.Reuse },
        { "Damage Weaken", EffectType.DamageWeaken },
        { "Damage Duplicate", EffectType.DamageDuplicate },
        { "Shield Duplicate", EffectType.ShieldDuplicate },
        { "Mana Duplicate", EffectType.ManaDuplicate },
        { "Damage Ranged Engage", EffectType.DamageRangedEngage },
        { "Revive", EffectType.Revive },
        { "Damage Rampage", EffectType.DamageRampage },
        { "Add DoubleUse", EffectType.AddDoubleUse },
        { "Add Cantrip", EffectType.AddCantrip },
        { "Add Nothing", EffectType.AddNothing },
        { "Add Copycat", EffectType.AddCopycat },
        { "Add Cleave Single-use", EffectType.AddCleaveSingleUse },
        { "Add Cruel Deathwish", EffectType.AddCruelDeathwish },
        { "Add ManaGain", EffectType.AddManaGain },
        { "Add Poison", EffectType.AddPoison },
        { "Add SelfShield", EffectType.AddSelfShield },
        { "Add SeflHeal", EffectType.AddSelfHeal },
        { "Add SelfHeal SelfShield", EffectType.AddSelfHealSelfShield },
        { "Add Pain ManaGain", EffectType.AddPainManaGain },
        { "Add Engage", EffectType.AddEngage },
        { "Add Growth", EffectType.AddGrowth },
        { "Blank (Shield)", EffectType.BlankShield },
        { "Blank (Damage)", EffectType.BlankDamage },
        { "Blank (Mana)", EffectType.BlankMana },
        { "Blank (Summon)", EffectType.BlankSummon },
        { "Blank (Heal)", EffectType.BlankHeal },
        { "Redirect Cleave - [Red Flag]", EffectType.RedirectCleave },
        { "Damage to ALL Rampage - [Spinning Scythe]", EffectType.DamageToAllRampage },
        { "Damage Flesh Pain - [Viscera]", EffectType.DamageFleshPain },
        { "Damage to ALL Charged ManaCost - [Mana Bomb]", EffectType.DamageToAllChargedManaCost },
        { "Damage SingleUse InflictSingleUse - [Wand of Wand]", EffectType.DamageSingleUseInflictSingleUse },
        { "Heal Boost InflictPain - [Demon Horn]", EffectType.HealBoostInflictPain },
        { "Damage Heavy Charged - [Charged Hammer]", EffectType.DamageHeavyCharged },
        { "Heal Regen Cleanse ManaCost - [Infused Herbs]", EffectType.HealRegenCleanseManaCost },
        { "Damage Pain Drink - [Potion Shard]", EffectType.DamagePainDrink },
        { "Revive Drink - [Revive Potion]", EffectType.ReviveDrink },
        { "Mana Drink - [Mana Potion]", EffectType.ManaDrink },
        { "Damage Eliminate", EffectType.DamageEliminate },
        { "Damage Poison (Enemy)", EffectType.DamagePoisonEnemy },
        { "Damage (Enemy)", EffectType.DamageEnemy },
        { "Damage Cleave (Enemy)", EffectType.DamageCleaveEnemy },
        { "Summon Dragons Death", EffectType.SummonDragonsDeath },
        { "Damage Cleave Trio", EffectType.DamageCleaveTrio },
        { "Damage Defy", EffectType.DamageDefy },
        { "Damage Critical", EffectType.DamageCritical },
        { "Target Ally", EffectType.TargetAlly },
        { "Target Ally (Pips)", EffectType.TargetAllyPips },
        { "All Allies (Pips)", EffectType.AllAlliesPips },
        { "All Allies ", EffectType.AllAllies },
        { "Target Enemy", EffectType.TargetEnemy },
        { "Target Enemy (Pips)", EffectType.TargetEnemyPips },
        { "All Enemies (Pips)", EffectType.AllEnemiesPips },
        { "All Enemies", EffectType.AllEnemies },
        { "Target ALL (Pips)", EffectType.TargetAllPips },
        { "Target ALL", EffectType.TargetAll },
        { "Target Self", EffectType.TargetSelf },
        { "Target Self (Pips)", EffectType.TargetSelfPips }
    };
}


[Serializable]
public class DiceSideData
{
    public int effectID = 0;
    public int pips = 0;

    // New Fields
    public List<string> keywords = new List<string>();
    public string facadeID = "";
    public string facadeColor = ""; // Can hold "41" or "h:s:v"
}

public static class DiceTargetHelper
{
    // Indices: 0:left, 1:mid, 2:top, 3:bot, 4:right, 5:rightmost
    public static readonly string[] FaceNames = { "left", "mid", "top", "bot", "right", "rightmost" };

    public static List<int> GetIndicesForTarget(string target)
    {
        target = target?.ToLower() ?? "";

        return target switch
        {
            "left" => new List<int> { 0 },
            "mid" => new List<int> { 1 },
            "top" => new List<int> { 2 },
            "bot" => new List<int> { 3 },
            "right" => new List<int> { 4 },
            "rightmost" => new List<int> { 5 },

            // Logic definitions
            "all" => new List<int> { 0, 1, 2, 3, 4, 5 },
            "row" => new List<int> { 0, 1, 4 },      // Middle Row: Left, Mid, Right
            "col" => new List<int> { 1, 2, 3 },      // Column: Mid, Top, Bot

            // Combinations
            "topbot" => new List<int> { 2, 3 },         // Top and Bottom
            "left2" => new List<int> { 0, 1 },         // Middle and left
            "mid2" => new List<int> { 1, 4 },         // Middle and right
            "right2" => new List<int> { 4, 5 },         // Right and rightmost
            "right3" => new List<int> { 1, 4, 5 },      // Middle, right and rightmost
            "right5" => new List<int> { 1, 2, 3, 4, 5 },// All except left

            _ => new List<int>()
        };
    }
}