using System.Collections.Generic;
using UnityEngine;

public enum KeywordColor
{
    Green,
    Purple,
    Grey,
    Yellow,
    Light,
    Red,
    Blue,
    Orange,
    Pink
}

public static class EffectKeywordColors
{
    // Color definitions
    public static readonly Color Green = new Color(0.3f, 0.8f, 0.3f);     // Readable green
    public static readonly Color Purple = new Color(0.65f, 0.35f, 0.85f);  // Soft purple
    public static readonly Color Grey = new Color(0.65f, 0.65f, 0.65f);    // Medium-light grey
    public static readonly Color Yellow = new Color(0.95f, 0.75f, 0.1f);   // Warm yellow/gold
    public static readonly Color Light = new Color(0.95f, 0.95f, 0.95f);     // Off-white/light blue-grey
    public static readonly Color Red = new Color(0.9f, 0.3f, 0.3f);        // Soft red
    public static readonly Color Blue = new Color(0.3f, 0.6f, 0.95f);      // Clear blue
    public static readonly Color Orange = new Color(0.95f, 0.5f, 0.1f);    // Warm orange
    public static readonly Color Pink = new Color(0.95f, 0.45f, 0.7f);     // Rose pink

    // Complete dictionary mapping every keyword to its corresponding Unity Color
    public static readonly Dictionary<EffectKeyword, Color> Map = new Dictionary<EffectKeyword, Color>
    {
        { EffectKeyword.Acidic, Green },
        { EffectKeyword.Affected, Purple },
        { EffectKeyword.Annul, Grey },
        { EffectKeyword.Antideathwish, Purple },
        { EffectKeyword.Antidog, Yellow },
        { EffectKeyword.Antiengage, Yellow },
        { EffectKeyword.Antipair, Light },
        { EffectKeyword.Antipristine, Light },
        { EffectKeyword.Armoured, Light },
        { EffectKeyword.Bloodlust, Red },
        { EffectKeyword.Boned, Light },
        { EffectKeyword.Boost, Blue },
        { EffectKeyword.Buffed, Light },
        { EffectKeyword.Bully, Orange },
        { EffectKeyword.Cantrip, Pink },
        { EffectKeyword.Century, Grey },
        { EffectKeyword.Chain, Pink },
        { EffectKeyword.Channel, Green },
        { EffectKeyword.Charged, Blue },
        { EffectKeyword.Cleanse, Light },
        { EffectKeyword.Cleave, Light },
        { EffectKeyword.Cooldown, Orange },
        { EffectKeyword.Copycat, Light },
        { EffectKeyword.Critical, Yellow },
        { EffectKeyword.Cruel, Orange },
        { EffectKeyword.Cruesh, Orange },
        { EffectKeyword.Damage, Orange },
        { EffectKeyword.Death, Light },
        { EffectKeyword.Deathlust, Purple },
        { EffectKeyword.Deathwish, Purple },
        { EffectKeyword.Decay, Purple },
        { EffectKeyword.Defy, Yellow },
        { EffectKeyword.Dejavu, Pink },
        { EffectKeyword.Deplete, Orange },
        { EffectKeyword.Descend, Light },
        { EffectKeyword.Dispel, Pink },
        { EffectKeyword.Dog, Yellow },
        { EffectKeyword.Dogma, Yellow },
        { EffectKeyword.DoubDiff, Yellow },
        { EffectKeyword.Doubled, Blue },
        { EffectKeyword.Doublegrowth, Green },
        { EffectKeyword.DoubleUse, Orange },
        { EffectKeyword.Duegue, Blue },
        { EffectKeyword.Duel, Blue },
        { EffectKeyword.Duplicate, Blue },
        { EffectKeyword.Echo, Blue },
        { EffectKeyword.Ego, Yellow },
        { EffectKeyword.Eliminate, Red },
        { EffectKeyword.Enduring, Grey },
        { EffectKeyword.Engage, Yellow },
        { EffectKeyword.Engarged, Yellow },
        { EffectKeyword.Engine, Yellow },
        { EffectKeyword.Equipped, Grey },
        { EffectKeyword.Era, Blue },
        { EffectKeyword.Evil, Red },
        { EffectKeyword.Exert, Grey },
        { EffectKeyword.Fashionable, Blue },
        { EffectKeyword.Fault, Blue },
        { EffectKeyword.Fierce, Yellow },
        { EffectKeyword.First, Light },
        { EffectKeyword.Fizz, Blue },
        { EffectKeyword.Flesh, Red },
        { EffectKeyword.Fluctuate, Blue },
        { EffectKeyword.Flurry, Orange },
        { EffectKeyword.Focus, Orange },
        { EffectKeyword.Fumble, Grey },
        { EffectKeyword.Future, Blue },
        { EffectKeyword.Generous, Light },
        { EffectKeyword.Groooooowth, Green },
        { EffectKeyword.Groupdecay, Purple },
        { EffectKeyword.Groupexert, Purple },
        { EffectKeyword.Groupgroooooowth, Green },
        { EffectKeyword.Groupgrowth, Green },
        { EffectKeyword.GroupsingleUse, Orange },
        { EffectKeyword.Growth, Green },
        { EffectKeyword.Guilt, Orange },
        { EffectKeyword.Halvedeathwish, Purple },
        { EffectKeyword.Halveduel, Blue },
        { EffectKeyword.Halveengage, Yellow },
        { EffectKeyword.Heal, Red },
        { EffectKeyword.Heavy, Yellow },
        { EffectKeyword.Hoard, Orange },
        { EffectKeyword.Hyena, Yellow },
        { EffectKeyword.Hyperboned, Light },
        { EffectKeyword.Hypergrowth, Green },
        { EffectKeyword.Hyperuse, Orange },
        { EffectKeyword.Hypnotise, Orange },
        { EffectKeyword.Inflictboned, Light },
        { EffectKeyword.Inflictdeath, Light },
        { EffectKeyword.Inflictexert, Purple },
        { EffectKeyword.Inflictinflictdeath, Light },
        { EffectKeyword.Inflictinflictnothing, Grey },
        { EffectKeyword.Inflictnothing, Grey },
        { EffectKeyword.Inflictpain, Red },
        { EffectKeyword.Inflictselfshield, Light },
        { EffectKeyword.InflictsingleUse, Orange },
        { EffectKeyword.Inspired, Green },
        { EffectKeyword.Lead, Yellow },
        { EffectKeyword.Lucky, Red },
        { EffectKeyword.Manacost, Purple },
        { EffectKeyword.ManaGain, Blue },
        { EffectKeyword.Mandatory, Red },
        { EffectKeyword.Minusera, Blue },
        { EffectKeyword.Minusflesh, Red },
        { EffectKeyword.Moxie, Yellow },
        { EffectKeyword.Nothing, Grey },
        { EffectKeyword.Onesie, Grey },
        { EffectKeyword.Overdog, Yellow },
        { EffectKeyword.Pain, Red },
        { EffectKeyword.Pair, Light },
        { EffectKeyword.Patient, Light },
        { EffectKeyword.Paxin, Light },
        { EffectKeyword.PermaBoost, Pink },
        { EffectKeyword.Permissive, Pink },
        { EffectKeyword.Petrify, Yellow },
        { EffectKeyword.Picky, Blue },
        { EffectKeyword.Plague, Green },
        { EffectKeyword.Plus, Grey },
        { EffectKeyword.Poison, Green },
        { EffectKeyword.Possessed, Purple },
        { EffectKeyword.Potion, Purple },
        { EffectKeyword.Pristeel, Light },
        { EffectKeyword.Pristine, Light },
        { EffectKeyword.Priswish, Light },
        { EffectKeyword.QuadUse, Orange },
        { EffectKeyword.Quin, Light },
        { EffectKeyword.Rainbow, Light },
        { EffectKeyword.Rampage, Purple },
        { EffectKeyword.Ranged, Light },
        { EffectKeyword.Reborn, Yellow },
        { EffectKeyword.Regen, Red },
        { EffectKeyword.Removed, Light },
        { EffectKeyword.Repel, Orange },
        { EffectKeyword.Rescue, Yellow },
        { EffectKeyword.Resilient, Orange },
        { EffectKeyword.Resonate, Pink },
        { EffectKeyword.RevDiff, Red },
        { EffectKeyword.Rite, Green },
        { EffectKeyword.Run, Yellow },
        { EffectKeyword.Scared, Purple },
        { EffectKeyword.Selfcleanse, Light },
        { EffectKeyword.Selfheal, Red },
        { EffectKeyword.Selfpetrify, Yellow },
        { EffectKeyword.Selfpoison, Green },
        { EffectKeyword.Selfregen, Red },
        { EffectKeyword.Selfrepel, Orange },
        { EffectKeyword.Selfshield, Light },
        { EffectKeyword.Selfvulnerable, Orange },
        { EffectKeyword.Sept, Light },
        { EffectKeyword.Serrated, Red },
        { EffectKeyword.Share, Light },
        { EffectKeyword.Shield, Grey },
        { EffectKeyword.Shifter, Pink },
        { EffectKeyword.SingleCast, Purple },
        { EffectKeyword.SingleUse, Orange },
        { EffectKeyword.Sixth, Orange },
        { EffectKeyword.Skill, Light },
        { EffectKeyword.Sloth, Light },
        { EffectKeyword.Smith, Light },
        { EffectKeyword.Spellrescue, Yellow },
        { EffectKeyword.Sprint, Orange },
        { EffectKeyword.Spy, Grey },
        { EffectKeyword.Squared, Pink },
        { EffectKeyword.Squish, Yellow },
        { EffectKeyword.Stasis, Blue },
        { EffectKeyword.Steel, Light },
        { EffectKeyword.Step, Grey },
        { EffectKeyword.Sticky, Purple },
        { EffectKeyword.Swapcruel, Orange },
        { EffectKeyword.Swapdeathwish, Purple },
        { EffectKeyword.Swapengage, Yellow },
        { EffectKeyword.Swapterminal, Purple },
        { EffectKeyword.Tactical, Orange },
        { EffectKeyword.Tall, Orange },
        { EffectKeyword.Terminal, Purple },
        { EffectKeyword.Threesy, Orange },
        { EffectKeyword.Treble, Light },
        { EffectKeyword.Trill, Light },
        { EffectKeyword.Trio, Light },
        { EffectKeyword.Underdog, Yellow },
        { EffectKeyword.Undergrowth, Green },
        { EffectKeyword.Underocus, Yellow },
        { EffectKeyword.Unusable, Grey },
        { EffectKeyword.Uppercut, Orange },
        { EffectKeyword.Vigil, Light },
        { EffectKeyword.Vitality, Light },
        { EffectKeyword.Vulnerable, Orange },
        { EffectKeyword.Weaken, Green },
        { EffectKeyword.Wham, Light },
        { EffectKeyword.Wither, Green },
        { EffectKeyword.Zeroed, Grey }
    };
}


public enum EffectKeyword
{
    Acidic,
    Affected,
    Annul,
    Antideathwish,
    Antidog,
    Antiengage,
    Antipair,
    Antipristine,
    Armoured,
    Bloodlust,
    Boned,
    Boost,
    Buffed,
    Bully,
    Cantrip,
    Century,
    Chain,
    Channel,
    Charged,
    Cleanse,
    Cleave,
    Cooldown,
    Copycat,
    Critical,
    Cruel,
    Cruesh,
    Damage,
    Death,
    Deathlust,
    Deathwish,
    Decay,
    Defy,
    Dejavu,
    Deplete,
    Descend,
    Dispel,
    Dog,
    Dogma,
    DoubDiff,
    Doubled,
    Doublegrowth,
    DoubleUse,
    Duegue,
    Duel,
    Duplicate,
    Echo,
    Ego,
    Eliminate,
    Enduring,
    Engage,
    Engarged,
    Engine,
    Equipped,
    Era,
    Evil,
    Exert,
    Fashionable,
    Fault,
    Fierce,
    First,
    Fizz,
    Flesh,
    Fluctuate,
    Flurry,
    Focus,
    Fumble,
    Future,
    Generous,
    Groooooowth,
    Groupdecay,
    Groupexert,
    Groupgroooooowth,
    Groupgrowth,
    GroupsingleUse,
    Growth,
    Guilt,
    Halvedeathwish,
    Halveduel,
    Halveengage,
    Heal,
    Heavy,
    Hoard,
    Hyena,
    Hyperboned,
    Hypergrowth,
    Hyperuse,
    Hypnotise,
    Inflictboned,
    Inflictdeath,
    Inflictexert,
    Inflictinflictdeath,
    Inflictinflictnothing,
    Inflictnothing,
    Inflictpain,
    Inflictselfshield,
    InflictsingleUse,
    Inspired,
    Lead,
    Lucky,
    Manacost,
    ManaGain,
    Mandatory,
    Minusera,
    Minusflesh,
    Moxie,
    Nothing,
    Onesie,
    Overdog,
    Pain,
    Pair,
    Patient,
    Paxin,
    PermaBoost,
    Permissive,
    Petrify,
    Picky,
    Plague,
    Plus,
    Poison,
    Possessed,
    Potion,
    Pristeel,
    Pristine,
    Priswish,
    QuadUse,
    Quin,
    Rainbow,
    Rampage,
    Ranged,
    Reborn,
    Regen,
    Removed,
    Repel,
    Rescue,
    Resilient,
    Resonate,
    RevDiff,
    Rite,
    Run,
    Scared,
    Selfcleanse,
    Selfheal,
    Selfpetrify,
    Selfpoison,
    Selfregen,
    Selfrepel,
    Selfshield,
    Selfvulnerable,
    Sept,
    Serrated,
    Share,
    Shield,
    Shifter,
    SingleCast,
    SingleUse,
    Sixth,
    Skill,
    Sloth,
    Smith,
    Spellrescue,
    Sprint,
    Spy,
    Squared,
    Squish,
    Stasis,
    Steel,
    Step,
    Sticky,
    Swapcruel,
    Swapdeathwish,
    Swapengage,
    Swapterminal,
    Tactical,
    Tall,
    Terminal,
    Threesy,
    Treble,
    Trill,
    Trio,
    Underdog,
    Undergrowth,
    Underocus,
    Unusable,
    Uppercut,
    Vigil,
    Vitality,
    Vulnerable,
    Weaken,
    Wham,
    Wither,
    Zeroed
}