#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

public static class HeroDatabaseGenerator
{
    private const string AtlasPath = "base_atlas_image";
    private const string OutputFilePath = "Assets/Scripts/HeroSpriteDatabase.cs";


    private static readonly Regex HeroSpriteRegex = new Regex(
        @"^([a-z]+)_(\d+)_([a-z\-]+?)((?:[RUL]\d+)+)?$",
        RegexOptions.IgnoreCase | RegexOptions.Compiled
    );

    private static readonly HashSet<string> ExcludedPrefixes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "ite", "fac", "ach", "ui", "tri", "ico", "pan", "str", "spe"
    };

    private struct SpriteMatchResult
    {
        public string SpriteName;
        public bool HasRankSuffix;
    }

    [MenuItem("Tools/Generate Hero Sprite Database")]
    public static void GenerateDatabase()
    {
        Sprite[] allSprites = Resources.LoadAll<Sprite>(AtlasPath);

        if (allSprites == null || allSprites.Length == 0)
        {
            Debug.LogError($"[Generator] Failed to load sprites from Resources/{AtlasPath}. Make sure the asset is properly sliced.");
            return;
        }

        AllHeroNames[] heroEnums = (AllHeroNames[])Enum.GetValues(typeof(AllHeroNames));
        StringBuilder dictionaryBody = new StringBuilder();

        foreach (AllHeroNames hero in heroEnums)
        {
            if (hero == AllHeroNames.None)
            {
                continue;
            }

            string enumName = hero.ToString();

            List<SpriteMatchResult> matches = new List<SpriteMatchResult>();

            foreach (Sprite sprite in allSprites)
            {
                Match match = HeroSpriteRegex.Match(sprite.name);
                if (match.Success)
                {
                    string prefix = match.Groups[1].Value;
                    string coreName = match.Groups[3].Value;
                    bool hasRank = match.Groups[4].Success && !string.IsNullOrEmpty(match.Groups[4].Value);

                    if (ExcludedPrefixes.Contains(prefix))
                    {
                        continue;
                    }

                    if (string.Equals(coreName, enumName, StringComparison.OrdinalIgnoreCase))
                    {
                        matches.Add(new SpriteMatchResult { SpriteName = sprite.name, HasRankSuffix = hasRank });
                    }
                }
            }

            // Fallback strategy
            if (matches.Count == 0)
            {
                foreach (Sprite sprite in allSprites)
                {
                    if (sprite.name.IndexOf(enumName, StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        matches.Add(new SpriteMatchResult { SpriteName = sprite.name, HasRankSuffix = false });
                    }
                }
            }

            // Tie-breaker prioritization
            if (matches.Count > 1)
            {
                List<SpriteMatchResult> rankedMatches = matches.FindAll(m => m.HasRankSuffix);
                if (rankedMatches.Count > 0)
                {
                    matches = rankedMatches;
                }
            }

            // Record successful matches in formatting
            if (matches.Count == 1)
            {
                dictionaryBody.AppendLine($"        {{ AllHeroNames.{hero}, \"{matches[0].SpriteName}\" }},");
            }
            else if (matches.Count > 1)
            {
                List<string> matchNames = matches.ConvertAll(m => m.SpriteName);
                Debug.LogWarning($"[Generator] Multiple matches for '{hero}' [{string.Join(", ", matchNames)}]. Skipped.");
            }
            else
            {
                Debug.LogWarning($"[Generator] No match found for '{hero}'. Skipped.");
            }
        }

        // Prepare file directory
        string directory = Path.GetDirectoryName(OutputFilePath);
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        // Generate class file content
        StringBuilder fileContent = new StringBuilder();
        fileContent.AppendLine("// ==========================================================================");
        fileContent.AppendLine("// <auto-generated>");
        fileContent.AppendLine("//     This code was generated by a tool.");
        fileContent.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        fileContent.AppendLine("//     the code is regenerated.");
        fileContent.AppendLine("//     Regenerate this name list if the base_atlas_image atlas ever changes how its named/parsed.");
        fileContent.AppendLine("// </auto-generated>");
        fileContent.AppendLine("// ==========================================================================");
        fileContent.AppendLine("using System.Collections.Generic;");
        fileContent.AppendLine();
        fileContent.AppendLine("public static class HeroSpriteDatabase");
        fileContent.AppendLine("{");
        fileContent.AppendLine("    // Explicit database mapping definitions to ensure accurate engine IDs");
        fileContent.AppendLine("    public static readonly Dictionary<AllHeroNames, string> HeroSpriteMap = new Dictionary<AllHeroNames, string>");
        fileContent.AppendLine("    {");
        fileContent.Append(dictionaryBody.ToString());
        fileContent.AppendLine("    };");
        fileContent.AppendLine("}");

        // Save file and update Unity's asset database
        File.WriteAllText(OutputFilePath, fileContent.ToString());
        AssetDatabase.Refresh();
        Debug.Log($"[Generator] Database script created at {OutputFilePath}");
    }
}
#endif