using System.Collections.Generic;
using System.Linq;

namespace SliceDiceTextMod
{
    // =========================================================
    // BASE CLASSES
    // =========================================================
    public abstract class ModDirectiveData
    {
        public string Id { get; private set; } = System.Guid.NewGuid().ToString();
        public int SortIndex { get; set; }
        public bool IsHidden { get; set; }
        public string FloorSelectorRaw { get; set; }
        public string ModName { get; set; } //.ms
        public string Doc{ get; set; } //.doc
        public int Part{ get; set; } //part.#
        public int Modtier{ get; set; } //modtier.#

        public abstract string ToModString();

        protected string ApplyWrappers(string coreData)
        {
            string output = coreData;
            if (!string.IsNullOrEmpty(FloorSelectorRaw))
                output = $"{FloorSelectorRaw}.{output}";

            if (IsHidden)
                output = $"!m({output})";

            return output;
        }
    }

    public abstract class PoolDirectiveData : ModDirectiveData
    {
        public List<string> Elements { get; set; } = new List<string>();
        protected abstract string Prefix { get; }

        public override string ToModString()
        {
            if (Elements == null || Elements.Count == 0) return "";
            string joined = string.Join("+", Elements.Where(e => !string.IsNullOrWhiteSpace(e)));
            return ApplyWrappers($"{Prefix}.{joined}");
        }
    }

    // =========================================================
    // 1. POOLS & INJECTIONS (Uses '+' delimited lists)
    // =========================================================
    public class MonsterPoolData : PoolDirectiveData { protected override string Prefix => "monsterpool"; }
    public class ItemPoolData : PoolDirectiveData { protected override string Prefix => "itempool"; }

    public class ForcedFightData : PoolDirectiveData { protected override string Prefix => "fight"; }
    public class SpawnInjectionData : PoolDirectiveData { protected override string Prefix => "add"; }
    public class PartyConfigData : PoolDirectiveData { protected override string Prefix => "party"; }

    // =========================================================
    // 2. CONFIGURATIONS (diff, zone, ritemx)
    // =========================================================
    public class ConfigDirectiveData : ModDirectiveData
    {
        public string Prefix { get; set; }
        public string Payload { get; set; }

        public override string ToModString() => ApplyWrappers($"{Prefix}.{Payload}");
    }

    // =========================================================
    // 3. TOGGLES & MACRO COMMANDS (From IDE Regex)
    // =========================================================
    public class ToggleDirectiveData : ModDirectiveData
    {
        public string ToggleName { get; set; }
        public override string ToModString() => ApplyWrappers($"tog{ToggleName}");
    }

    public class CommandDirectiveData : ModDirectiveData
    {
        // Holds commands like "Delevel", "Level Up", "skip all", "No Flee", "temporary"
        public string Command { get; set; }
        public override string ToModString() => ApplyWrappers(Command);
    }

    // =========================================================
    // 4. CUSTOM ENTITIES / MODIFIERS
    // =========================================================
    public class CustomEntityData : ModDirectiveData
    {
        // This holds strings generated by HeroModManager, Item Builders, etc.
        // e.g., "replica.Statue.n.MyHero.hp.10.sd.1-1:2-2..."
        public string EntitySyntax { get; set; }

        public override string ToModString() => ApplyWrappers(EntitySyntax);
    }

    // =========================================================
    // 5. LOGIC & PHASES (ph., phi., phmp., !)
    // =========================================================
    public class PhaseEventData : ModDirectiveData
    {
        public Phase PhaseObj { get; set; }

        public override string ToModString()
        {
            if (PhaseObj == null) return "";

            PhaseObj.FloorSelector = !string.IsNullOrEmpty(FloorSelectorRaw)
                ? FloorSelector.TryParse(FloorSelectorRaw)
                : null;

            string output = PhaseObj.ToSyntax(omitPrefix: false);
            return IsHidden ? $"!m({output})" : output;
        }
    }

    // =========================================================
    // 6. CHOOSABLE REWARDS (ch.m, ch.i, etc)
    // =========================================================
    public class RewardOptionData : ModDirectiveData
    {
        public RewardTag RewardObj { get; set; }

        public override string ToModString()
        {
            if (RewardObj == null) return "";
            string output = $"ch.{RewardObj.ToSyntax()}";
            return ApplyWrappers(output);
        }
    }

    // =========================================================
    // 7. RAW FALLBACK
    // =========================================================
    public class RawDirectiveData : ModDirectiveData
    {
        public string RawContent { get; set; }
        public override string ToModString() => RawContent;
    }
}